[package]
name = "rocket_fs"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.4.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.rocket_contrib]
version = "0.4.10"
default-features = false
features = ["tera_templates"]
